-- ==========================================================================
-- AVEAM ASSEMBLY PROGRESS TRACKER - SUPABASE DATABASE INITIALIZATION SQL
-- Copy and paste this script into your Supabase SQL Editor and click "Run".
-- ==========================================================================

-- 1. Create Projects Table (Tracks current WIP status and sub-assemblies)
CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    customer TEXT NOT NULL,
    project_code TEXT NOT NULL,
    part_number TEXT,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'ontime',
    team_leader TEXT,
    member_1 TEXT,
    job_no TEXT NOT NULL,
    mc_number TEXT,
    progress INTEGER NOT NULL DEFAULT 0,
    qty INTEGER NOT NULL DEFAULT 1,
    qty_done INTEGER NOT NULL DEFAULT 0, -- Cumulative Finish Goods
    est_hours NUMERIC DEFAULT 0,
    sub_assemblies JSONB, -- Stores array of sub-assembly steps and progress
    kanban_backlog INTEGER NOT NULL DEFAULT 0,
    kanban_assigned INTEGER NOT NULL DEFAULT 0,
    kanban_in_progress INTEGER NOT NULL DEFAULT 0,
    kanban_qa INTEGER NOT NULL DEFAULT 0,
    kanban_completed INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Updates Table (Tracks daily historical logs of worker reports)
CREATE TABLE IF NOT EXISTS updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    reporter TEXT NOT NULL,
    customer TEXT,
    project_code TEXT,
    job_number TEXT,
    progress INTEGER,
    qty_done INTEGER DEFAULT 0, -- Daily Finish Goods quantity reported
    issue TEXT,
    note TEXT
);

-- 3. Enable Realtime database listening for the projects table
-- This allows the TV monitor dashboard to update instantly when workers save data
alter publication supabase_realtime add table projects;

-- 4. Set up Table Policies (Row Level Security - RLS) for simple access
-- By default, RLS is disabled. You can keep it disabled for local development.
-- If RLS is enabled, you can run these policies to allow read/write:
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE updates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read projects" ON projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update projects" ON projects FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read updates" ON updates FOR SELECT USING (true);
CREATE POLICY "Allow public insert updates" ON updates FOR INSERT WITH CHECK (true);
